// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encryption.proto

#ifndef PROTOBUF_encryption_2eproto__INCLUDED
#define PROTOBUF_encryption_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include "sync/base/sync_export.h"

namespace sync_pb {

// Internal implementation detail -- do not call these.
void SYNC_EXPORT protobuf_AddDesc_encryption_2eproto();
void protobuf_AssignDesc_encryption_2eproto();
void protobuf_ShutdownFile_encryption_2eproto();

class EncryptedData;

// ===================================================================

class SYNC_EXPORT EncryptedData : public ::google::protobuf::MessageLite {
 public:
  EncryptedData();
  virtual ~EncryptedData();

  EncryptedData(const EncryptedData& from);

  inline EncryptedData& operator=(const EncryptedData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const EncryptedData& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EncryptedData* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EncryptedData* other);

  // implements Message ----------------------------------------------

  EncryptedData* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EncryptedData& from);
  void MergeFrom(const EncryptedData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key_name = 1;
  inline bool has_key_name() const;
  inline void clear_key_name();
  static const int kKeyNameFieldNumber = 1;
  inline const ::std::string& key_name() const;
  inline void set_key_name(const ::std::string& value);
  inline void set_key_name(const char* value);
  inline void set_key_name(const char* value, size_t size);
  inline ::std::string* mutable_key_name();
  inline ::std::string* release_key_name();
  inline void set_allocated_key_name(::std::string* key_name);

  // optional string blob = 2;
  inline bool has_blob() const;
  inline void clear_blob();
  static const int kBlobFieldNumber = 2;
  inline const ::std::string& blob() const;
  inline void set_blob(const ::std::string& value);
  inline void set_blob(const char* value);
  inline void set_blob(const char* value, size_t size);
  inline ::std::string* mutable_blob();
  inline ::std::string* release_blob();
  inline void set_allocated_blob(::std::string* blob);

  // @@protoc_insertion_point(class_scope:sync_pb.EncryptedData)
 private:
  inline void set_has_key_name();
  inline void clear_has_key_name();
  inline void set_has_blob();
  inline void clear_has_blob();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* key_name_;
  ::std::string* blob_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void SYNC_EXPORT protobuf_AddDesc_encryption_2eproto_impl();
  #else
  friend void SYNC_EXPORT protobuf_AddDesc_encryption_2eproto();
  #endif
  friend void protobuf_AssignDesc_encryption_2eproto();
  friend void protobuf_ShutdownFile_encryption_2eproto();

  void InitAsDefaultInstance();
  static EncryptedData* default_instance_;
};
// ===================================================================


// ===================================================================

// EncryptedData

// optional string key_name = 1;
inline bool EncryptedData::has_key_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EncryptedData::set_has_key_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EncryptedData::clear_has_key_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EncryptedData::clear_key_name() {
  if (key_name_ != &::google::protobuf::internal::GetEmptyString()) {
    key_name_->clear();
  }
  clear_has_key_name();
}
inline const ::std::string& EncryptedData::key_name() const {
  return *key_name_;
}
inline void EncryptedData::set_key_name(const ::std::string& value) {
  set_has_key_name();
  if (key_name_ == &::google::protobuf::internal::GetEmptyString()) {
    key_name_ = new ::std::string;
  }
  key_name_->assign(value);
}
inline void EncryptedData::set_key_name(const char* value) {
  set_has_key_name();
  if (key_name_ == &::google::protobuf::internal::GetEmptyString()) {
    key_name_ = new ::std::string;
  }
  key_name_->assign(value);
}
inline void EncryptedData::set_key_name(const char* value, size_t size) {
  set_has_key_name();
  if (key_name_ == &::google::protobuf::internal::GetEmptyString()) {
    key_name_ = new ::std::string;
  }
  key_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EncryptedData::mutable_key_name() {
  set_has_key_name();
  if (key_name_ == &::google::protobuf::internal::GetEmptyString()) {
    key_name_ = new ::std::string;
  }
  return key_name_;
}
inline ::std::string* EncryptedData::release_key_name() {
  clear_has_key_name();
  if (key_name_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = key_name_;
    key_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void EncryptedData::set_allocated_key_name(::std::string* key_name) {
  if (key_name_ != &::google::protobuf::internal::GetEmptyString()) {
    delete key_name_;
  }
  if (key_name) {
    set_has_key_name();
    key_name_ = key_name;
  } else {
    clear_has_key_name();
    key_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// optional string blob = 2;
inline bool EncryptedData::has_blob() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EncryptedData::set_has_blob() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EncryptedData::clear_has_blob() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EncryptedData::clear_blob() {
  if (blob_ != &::google::protobuf::internal::GetEmptyString()) {
    blob_->clear();
  }
  clear_has_blob();
}
inline const ::std::string& EncryptedData::blob() const {
  return *blob_;
}
inline void EncryptedData::set_blob(const ::std::string& value) {
  set_has_blob();
  if (blob_ == &::google::protobuf::internal::GetEmptyString()) {
    blob_ = new ::std::string;
  }
  blob_->assign(value);
}
inline void EncryptedData::set_blob(const char* value) {
  set_has_blob();
  if (blob_ == &::google::protobuf::internal::GetEmptyString()) {
    blob_ = new ::std::string;
  }
  blob_->assign(value);
}
inline void EncryptedData::set_blob(const char* value, size_t size) {
  set_has_blob();
  if (blob_ == &::google::protobuf::internal::GetEmptyString()) {
    blob_ = new ::std::string;
  }
  blob_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EncryptedData::mutable_blob() {
  set_has_blob();
  if (blob_ == &::google::protobuf::internal::GetEmptyString()) {
    blob_ = new ::std::string;
  }
  return blob_;
}
inline ::std::string* EncryptedData::release_blob() {
  clear_has_blob();
  if (blob_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = blob_;
    blob_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void EncryptedData::set_allocated_blob(::std::string* blob) {
  if (blob_ != &::google::protobuf::internal::GetEmptyString()) {
    delete blob_;
  }
  if (blob) {
    set_has_blob();
    blob_ = blob;
  } else {
    clear_has_blob();
    blob_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sync_pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_encryption_2eproto__INCLUDED
