// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension_setting_specifics.proto

#ifndef PROTOBUF_extension_5fsetting_5fspecifics_2eproto__INCLUDED
#define PROTOBUF_extension_5fsetting_5fspecifics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include "sync/base/sync_export.h"

namespace sync_pb {

// Internal implementation detail -- do not call these.
void SYNC_EXPORT protobuf_AddDesc_extension_5fsetting_5fspecifics_2eproto();
void protobuf_AssignDesc_extension_5fsetting_5fspecifics_2eproto();
void protobuf_ShutdownFile_extension_5fsetting_5fspecifics_2eproto();

class ExtensionSettingSpecifics;

// ===================================================================

class SYNC_EXPORT ExtensionSettingSpecifics : public ::google::protobuf::MessageLite {
 public:
  ExtensionSettingSpecifics();
  virtual ~ExtensionSettingSpecifics();

  ExtensionSettingSpecifics(const ExtensionSettingSpecifics& from);

  inline ExtensionSettingSpecifics& operator=(const ExtensionSettingSpecifics& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ExtensionSettingSpecifics& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ExtensionSettingSpecifics* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ExtensionSettingSpecifics* other);

  // implements Message ----------------------------------------------

  ExtensionSettingSpecifics* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ExtensionSettingSpecifics& from);
  void MergeFrom(const ExtensionSettingSpecifics& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string extension_id = 1;
  inline bool has_extension_id() const;
  inline void clear_extension_id();
  static const int kExtensionIdFieldNumber = 1;
  inline const ::std::string& extension_id() const;
  inline void set_extension_id(const ::std::string& value);
  inline void set_extension_id(const char* value);
  inline void set_extension_id(const char* value, size_t size);
  inline ::std::string* mutable_extension_id();
  inline ::std::string* release_extension_id();
  inline void set_allocated_extension_id(::std::string* extension_id);

  // optional string key = 2;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 2;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // optional string value = 3;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:sync_pb.ExtensionSettingSpecifics)
 private:
  inline void set_has_extension_id();
  inline void clear_has_extension_id();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* extension_id_;
  ::std::string* key_;
  ::std::string* value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void SYNC_EXPORT protobuf_AddDesc_extension_5fsetting_5fspecifics_2eproto_impl();
  #else
  friend void SYNC_EXPORT protobuf_AddDesc_extension_5fsetting_5fspecifics_2eproto();
  #endif
  friend void protobuf_AssignDesc_extension_5fsetting_5fspecifics_2eproto();
  friend void protobuf_ShutdownFile_extension_5fsetting_5fspecifics_2eproto();

  void InitAsDefaultInstance();
  static ExtensionSettingSpecifics* default_instance_;
};
// ===================================================================


// ===================================================================

// ExtensionSettingSpecifics

// optional string extension_id = 1;
inline bool ExtensionSettingSpecifics::has_extension_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ExtensionSettingSpecifics::set_has_extension_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ExtensionSettingSpecifics::clear_has_extension_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ExtensionSettingSpecifics::clear_extension_id() {
  if (extension_id_ != &::google::protobuf::internal::GetEmptyString()) {
    extension_id_->clear();
  }
  clear_has_extension_id();
}
inline const ::std::string& ExtensionSettingSpecifics::extension_id() const {
  return *extension_id_;
}
inline void ExtensionSettingSpecifics::set_extension_id(const ::std::string& value) {
  set_has_extension_id();
  if (extension_id_ == &::google::protobuf::internal::GetEmptyString()) {
    extension_id_ = new ::std::string;
  }
  extension_id_->assign(value);
}
inline void ExtensionSettingSpecifics::set_extension_id(const char* value) {
  set_has_extension_id();
  if (extension_id_ == &::google::protobuf::internal::GetEmptyString()) {
    extension_id_ = new ::std::string;
  }
  extension_id_->assign(value);
}
inline void ExtensionSettingSpecifics::set_extension_id(const char* value, size_t size) {
  set_has_extension_id();
  if (extension_id_ == &::google::protobuf::internal::GetEmptyString()) {
    extension_id_ = new ::std::string;
  }
  extension_id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ExtensionSettingSpecifics::mutable_extension_id() {
  set_has_extension_id();
  if (extension_id_ == &::google::protobuf::internal::GetEmptyString()) {
    extension_id_ = new ::std::string;
  }
  return extension_id_;
}
inline ::std::string* ExtensionSettingSpecifics::release_extension_id() {
  clear_has_extension_id();
  if (extension_id_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = extension_id_;
    extension_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void ExtensionSettingSpecifics::set_allocated_extension_id(::std::string* extension_id) {
  if (extension_id_ != &::google::protobuf::internal::GetEmptyString()) {
    delete extension_id_;
  }
  if (extension_id) {
    set_has_extension_id();
    extension_id_ = extension_id;
  } else {
    clear_has_extension_id();
    extension_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// optional string key = 2;
inline bool ExtensionSettingSpecifics::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ExtensionSettingSpecifics::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ExtensionSettingSpecifics::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ExtensionSettingSpecifics::clear_key() {
  if (key_ != &::google::protobuf::internal::GetEmptyString()) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& ExtensionSettingSpecifics::key() const {
  return *key_;
}
inline void ExtensionSettingSpecifics::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyString()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void ExtensionSettingSpecifics::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyString()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void ExtensionSettingSpecifics::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyString()) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ExtensionSettingSpecifics::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyString()) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* ExtensionSettingSpecifics::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void ExtensionSettingSpecifics::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::GetEmptyString()) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// optional string value = 3;
inline bool ExtensionSettingSpecifics::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ExtensionSettingSpecifics::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ExtensionSettingSpecifics::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ExtensionSettingSpecifics::clear_value() {
  if (value_ != &::google::protobuf::internal::GetEmptyString()) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& ExtensionSettingSpecifics::value() const {
  return *value_;
}
inline void ExtensionSettingSpecifics::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyString()) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void ExtensionSettingSpecifics::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyString()) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void ExtensionSettingSpecifics::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyString()) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ExtensionSettingSpecifics::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyString()) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* ExtensionSettingSpecifics::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void ExtensionSettingSpecifics::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::GetEmptyString()) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sync_pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_extension_5fsetting_5fspecifics_2eproto__INCLUDED
